# features/features.py
# Day 2: Feature Engineering – Save ML-ready features

import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt

import os

# Get the folder where this script is located
script_dir = os.path.dirname(os.path.abspath(__file__))

RAW_FOLDER = os.path.join(script_dir, "../data/raw")
PROCESSED_FOLDER = os.path.join(script_dir, "../data/processed")

raw_csv_path = os.path.join(RAW_FOLDER, "all_market_data.csv")
processed_csv_path = os.path.join(PROCESSED_FOLDER, "market_features.csv")

# MultiIndex CSV: first level = Open/High/Low/Close/Volume, second level = ticker symbol
data = pd.read_csv(raw_csv_path, header=[0,1], index_col=0, parse_dates=True)
print("Raw data loaded ✅")
print(f"Tickers found: {data['Close'].columns.tolist()}")

# --- 4️⃣ Extract tickers dynamically from 'Close' ---
tickers = data['Close'].columns.tolist()

# --- 5️⃣ Initialize features DataFrame ---
features = pd.DataFrame(index=data.index)

# --- 6️⃣ Calculate features for each ticker ---
for ticker in tickers:
    close = data['Close'][ticker]

    # Daily returns (main feature for direction prediction)
    features[f'{ticker}_daily_return'] = close.pct_change(fill_method=None)
    
    # 14-day rolling volatility (risk measure)
    features[f'{ticker}_volatility_14d'] = close.pct_change(fill_method=None).rolling(window=14).std()
    
    # 14-day momentum (trend strength)
    features[f'{ticker}_momentum_14d'] = close - close.shift(14)

# --- 7️⃣ Clean NaNs generated by rolling windows ---
features = features.dropna()  # drops first few rows without enough history

# --- 8️⃣ Save features CSV ---
features.to_csv(processed_csv_path)
print(f"Features saved to: {os.path.abspath(processed_csv_path)} ✅")

# --- 9️⃣ Optional: Visualize a sample feature ---
plt.figure(figsize=(12,6))
plt.plot(features['BTC-USD_daily_return'], label='BTC-USD Daily Return')
plt.title('BTC-USD Daily Return – Sample Check')
plt.xlabel('Date')
plt.ylabel('Return')
plt.legend()
plt.show()
